version: "{build}"
branches:
  except:
    - gh-pages
install:
  - set RUBY_HOME=C:\Ruby%ruby_version%
  - set PATH=%RUBY_HOME%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --no-document
  - bundle --version
  - bundle install
test_script:
  - bundle exec rake spec
build: off
deploy: off
environment:
  matrix:
    - ruby_version: 22
    - ruby_version: 22-x64
